export const PERSONAL_INFO = {
    name: "AMAN GANGWAR",
    email: "amangangwar70@gmail.com",
    role: "DIGITAL MARKETER",
    tagline: "WELCOME TO THE DIGITAL EDGE",
    bio: "WHERE CREATIVITY MEETS STRATEGY AND IDEAS TURN INTO MEASURABLE SUCCESS. I CRAFT DIGITAL EXPERIENCES THAT CONNECT BRAND WITH PEOPLE THROGH SMART MARKETING,COMPELLING CONTENT AND DATA DRIVEN RESULTS. LET'S MAKE YOUR BRAND IMPOSSIBLE TO IGNORE",
}